from app.exceptions import DefaultExceptions


class UserExceptions(DefaultExceptions):
    pass
